name: Github Action (CI/CD) for Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            echo "========= Github Action for Pulling Data"
            cd ~/public_html/spentra-tall/main-apps
            git checkout main
            git reset --hard
            git pull origin main
            # Copy Remote .env
            cp .env.remote .env
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Github Action via SSH (to Hosting)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            echo "========= Sync Public Directory (Except index.php, etc)"
            cd ~/public_html/spentra-tall
            rm -rf assets mix-manifest.json
            cd ~/public_html/spentra-tall/main-apps
            shopt -s extglob
            mv ~/public_html/spentra-tall/main-apps/public/!(index.php|files|livewire-tmp|.htaccess) ~/public_html/spentra-tall
      - name: Cleaning Cache, etc
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            pwd
            cd ~/public_html/spentra-tall/main-apps
            echo "========= Clear Laravel Cache"
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear